# Generated by Django 3.1.8 on 2021-07-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_key',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
