# Generated by Django 3.1.8 on 2021-07-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0002_comment_video_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video_key',
            new_name='videoId',
        ),
    ]
