# Generated by Django 3.1.8 on 2021-07-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0003_auto_20210723_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.comment'),
        ),
    ]
